embeddings {
  tensor_name: "day_of_week:00458"
  metadata_path: "00458/day_of_week\\metadata.tsv"
  tensor_path: "00458/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "month:00458"
  metadata_path: "00458/month\\metadata.tsv"
  tensor_path: "00458/month\\tensors.tsv"
}
embeddings {
  tensor_name: "Year:00458"
  metadata_path: "00458/Year\\metadata.tsv"
  tensor_path: "00458/Year\\tensors.tsv"
}
embeddings {
  tensor_name: "Quarter:00458"
  metadata_path: "00458/Quarter\\metadata.tsv"
  tensor_path: "00458/Quarter\\tensors.tsv"
}
