embeddings {
  tensor_name: "day_of_week:01300"
  metadata_path: "01300/day_of_week\\metadata.tsv"
  tensor_path: "01300/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "month:01300"
  metadata_path: "01300/month\\metadata.tsv"
  tensor_path: "01300/month\\tensors.tsv"
}
embeddings {
  tensor_name: "Year:01300"
  metadata_path: "01300/Year\\metadata.tsv"
  tensor_path: "01300/Year\\tensors.tsv"
}
embeddings {
  tensor_name: "Quarter:01300"
  metadata_path: "01300/Quarter\\metadata.tsv"
  tensor_path: "01300/Quarter\\tensors.tsv"
}
