embeddings {
  tensor_name: "day_of_week:00975"
  metadata_path: "00975/day_of_week\\metadata.tsv"
  tensor_path: "00975/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "month:00975"
  metadata_path: "00975/month\\metadata.tsv"
  tensor_path: "00975/month\\tensors.tsv"
}
embeddings {
  tensor_name: "Year:00975"
  metadata_path: "00975/Year\\metadata.tsv"
  tensor_path: "00975/Year\\tensors.tsv"
}
embeddings {
  tensor_name: "Quarter:00975"
  metadata_path: "00975/Quarter\\metadata.tsv"
  tensor_path: "00975/Quarter\\tensors.tsv"
}
