embeddings {
  tensor_name: "day_of_week:01694"
  metadata_path: "01694/day_of_week\\metadata.tsv"
  tensor_path: "01694/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "month:01694"
  metadata_path: "01694/month\\metadata.tsv"
  tensor_path: "01694/month\\tensors.tsv"
}
embeddings {
  tensor_name: "Year:01694"
  metadata_path: "01694/Year\\metadata.tsv"
  tensor_path: "01694/Year\\tensors.tsv"
}
embeddings {
  tensor_name: "Quarter:01694"
  metadata_path: "01694/Quarter\\metadata.tsv"
  tensor_path: "01694/Quarter\\tensors.tsv"
}
