embeddings {
  tensor_name: "day_of_week:00594"
  metadata_path: "00594/day_of_week\\metadata.tsv"
  tensor_path: "00594/day_of_week\\tensors.tsv"
}
embeddings {
  tensor_name: "month:00594"
  metadata_path: "00594/month\\metadata.tsv"
  tensor_path: "00594/month\\tensors.tsv"
}
embeddings {
  tensor_name: "Year:00594"
  metadata_path: "00594/Year\\metadata.tsv"
  tensor_path: "00594/Year\\tensors.tsv"
}
embeddings {
  tensor_name: "Quarter:00594"
  metadata_path: "00594/Quarter\\metadata.tsv"
  tensor_path: "00594/Quarter\\tensors.tsv"
}
embeddings {
  tensor_name: "Is_default:00594"
  metadata_path: "00594/Is_default\\metadata.tsv"
  tensor_path: "00594/Is_default\\tensors.tsv"
}
